apiVersion: v1
kind: Namespace
metadata:
  name: crdsdev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: doc-repos
  namespace: crdsdev
data:
  repos: |
    crossplane/crossplane,
    crossplane/provider-alibaba,
    crossplane/provider-aws,
    crossplane/provider-azure,
    crossplane/provider-gcp,
    crossplane/provider-rook,
    crossplane/oam-kubernetes-runtime,
    crossplane-contrib/provider-helm,
    jetstack/cert-manager,
    kubernetes-sigs/cluster-api,
    kubernetes-sigs/cluster-api-provider-packet,
    kubernetes-sigs/security-profiles-operator,
    packethost/crossplane-provider-packet,
    projectcontour/contour,
    schemahero/schemahero