apiVersion: v1
kind: ConfigMap
metadata:
  name: private-repos-auth
  namespace: crdsdev
data:
  repos.yaml: |-
    repos:
     - name: owner/private-repository
       server: github.mycompany.com
       user:
         name: machineuser
         pwdFromEnv: MACHINE_SECRET
